### ISSUE TITLE
Allow more control over compression

### ISSUE THREAD

**Issue by dcoutts** [Happstack/happstack-server#15]
The `Happstack.Server.Internal.Compression` exports some useful things but not quite enough...

The use case here is to control the level of compression used by gzip/zlib(deflate) compression. This is because there's an obvious tradeoff in cpu load vs transfer size. For hackage we want to serve range requests on the 00-index.tar but we want to allow those to use transfer compression. I've determined that zlib compression level 3 is the best tradeoff in cpu use vs transfer size, but the default is 6.

So, currently the `Happstack.Server.Internal.Compression` module exports the "do it all - but no control" `compressedResponseFilter`, and then the `compressWithFilter` and related actions that just compress the response. If one takes the latter route one has to re-implement the compression negotiation that `compressedResponseFilter` does. So my suggestion is that there should be a variant of `compressedResponseFilter` that takes as an argument the `allEncodingHandlers` that is currently hard coded. That way, we could call it with our own entry for "gzip" or "deflate" where we control the compression params exactly as we like.

**Comment by stepcut** [comment]
Two questions:

 1. any name suggestions? `compressedResponseFilterUsingHandlers` seems quite verbose. The happstack standard would be `compressedResponseFilter'` I guess. Though I am less pleased with that naming scheme these days.

 2. any opinion as to whether this should be an `Map` instead of an assoc list:

    allEncodingHandlers:: (FilterMonad Response m) => [(String, String -> Bool -> m ())]

There are currently only 5 entries in the list and the only operation is a 'lookup'. I can change it now, but after it is exported it would require an API bump.
