### ISSUE TITLE
Cookie values give me headaches

### ISSUE THREAD

**Issue by RamiroPastor** [Happstack/happstack-server#46]
Context: 

```
putCookieUserErrorMsg :: String -> ServerPart ()
putCookieUserErrorMsg err =
  addCookies
    [ (,) (MaxAge 300) (mkCookie "user-error-msg" err)
    ]

getCookieUserErrorMsg :: ServerPart (Maybe String)
getCookieUserErrorMsg = do
  m <- optional $ lookCookieValue "user-error-msg"
  -- _ <- expireCookie "user-error-msg"
  return m
```
Problematic string:

```
msg :: String
msg = "Error en la dirección email: \n no existe"
```

Yesterday i spent some time fixing the first issue, the `\n` character, which always resulted in `Nothing` when reading that cookie.

I removed the `\n` (which i agree was my mistake), but Firefox now displays (after converting the cookie string into Html with Blaze `toHtml`) :

`Error en la direcciï¿½n email: no existe`

although Chrome correctly displays 

`Error en la dirección email: no existe`

However both browsers, when inspecting the cookie, show 

`Error en la direcci�n email: no existe`

(enclosed by one pair of " in Chrome and two pairs of " in Firefox).

Is this an expected behaviour? should i manually use `unEscape` from `Happstack.Server.SURI` somewhere? should i restrict myself to very simple cookie values?

**Comment by RamiroPastor** [comment]
Same problem with ñ:

`Error: la contraseï¿½a es incorrecta`

**Comment by stepcut** [comment]
Hello!

You are not alone. The HTTP 1.1 specification does not really allow for Unicode in the cookie values. But, there does seem to be an adhoc standard for supporting it - because it is obviously a desirable thing to do.

Here is one place with a bit of background and work arounds,

https://stackoverflow.com/questions/28507778/how-to-safely-store-unicode-characters-in-cookies

It sounds like maybe we could perhaps modify the `addCookie` and `getCookies` functions to always do the required encoding and then you wouldn't have to do anything special?

If that fixes your problem and does not affect plain old ASCII cookies I'd be happy to merge a pull request.

**Comment by amcvega** [comment]
I was using Base64 encoding to ensure my authentication bytestrings were playing well with cookies and somehow the paddings were being url-encoded. Consequently the decoder was throwing errors. 

Until I tracked this issue down, I could not find any indication that `mkCookie` was manipulating my data before sticking it into a cookie. I also eventually figured out that one needs to use `Happstack.Server.SURI.percentDecode` to undo the manipulation although it was not apparent apart from going through the discussion.

I'm adding this comment just to note that this could be an issue for future users as well.
